# Generated by Django 5.1 on 2026-02-19 18:49

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
