# Generated by Django 4.2.29 on 2026-03-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagam',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
